### ISSUE TITLE
Reload recaptcha

### ISSUE THREAD

**Issue by fatihayyildiz** [mllrsohn/angular-re-captcha#14]
Hi there,

I'm using this module but I am stuck.For example if user type captcha wrong, behaviour will be reload recaptcha image without refresh the page. But I didn't find a document for this problem. If you want I can provide you code.I am using Angular.js

Thanks

**Comment by steffenmllr** [comment]
`reCAPTCHA.reload()` - have a look at: https://github.com/mllrsohn/angular-re-captcha/blob/master/angular-re-captcha.js#L59-L61

**Comment by fatihayyildiz** [comment]
Yes it's help.Many thanks !
