### ISSUE TITLE
Any text still form is valid

### ISSUE THREAD

**Issue by dalexandrov** [mllrsohn/angular-re-captcha#15]
Hello,
great stuff you've done! Thank you!

But a small issue: I can enter any text in captcha.. still the form is valid.
I've followed  the setup from the example.

Best regards,

Dmitry

**Comment by steffenmllr** [comment]
It only displays the  captcha and validates if you enter something in the input. The validation has to be done in the backend. Have a look at: https://developers.google.com/recaptcha/docs/verify

**Comment by dalexandrov** [comment]
Thank you!

**Comment by dalexandrov** [comment]
Hello once again..
sorry for bothering you. but...

so I've made my keys for that stuff , I've added the public key to configuration. 
Now i want to check the response at serverside. So i make a request to https://www.google.com/recaptcha/api/siteverify with secret=<my private key> and responce=<i take it from $scope.user.captcha.responce>
And it gives me an error...
