### ISSUE TITLE
Ability to set public key later than in .config()

### ISSUE THREAD

**Issue by madvas** [mllrsohn/angular-re-captcha#18]
It would be nice, if one could set public key in later phase of angular app. Some applications load their config data after angular is bootstrapped.

Thanks! Good job with the module ;)
Matus

**Comment by steffenmllr** [comment]
How do you load your config data? via ajax or boostaped in the html ?

**Comment by madvas** [comment]
It's set as angular value, rendered via Jinja2 template engine. No ajax
```
<script type="text/javascript">
    var module = angular.module('myModule');
    module.value('AppConfig', {{ app_config | tojson | safe }});
</script>
```

**Comment by steffenmllr** [comment]
Hmm you would have to do something like this:

```
var module = angular.module('myModule');
module.value('AppConfig', {{ app_config | tojson | safe }}).config(function (reCAPTCHAProvider) {
    reCAPTCHAProvider.setPublicKey({{app_config.reCAPTCHA.key}});
});
```

You could also fork it and and add a `setPublicKey` method to the factory with sets the `_publicKey ` var https://github.com/mllrsohn/angular-re-captcha/blob/master/angular-re-captcha.js#L2

Don't forget to send a PR :)
