### ISSUE TITLE
How to validate the captcha 

### ISSUE THREAD

**Issue by niyazhussain** [mllrsohn/angular-re-captcha#23]
Please provide an idea for how to validate the captcha,i tried with google api but it always returns false response.

**Comment by oguzcam58** [comment]
Hello  niyazgit,

You may see how I have done that before in my git account. 
Related project can be seen with the link below.
https://github.com/oguzcam58/spring-redis-angular

**Comment by dotcom9** [comment]
This example uses a different angular recapture directive. How do you get hold of the user response token to pass the google api from the angular-re-captcha directive? I haven't been able to work this out either.
